# Generated by Django 6.0.5 on 2026-06-13 09:06

import uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePlay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('game_session_id', models.TextField(unique=True)),
                ('game_type', models.TextField()),
                ('play_source', models.TextField(choices=[('order', 'Order'), ('rewarded_ad', 'Rewarded Ad')], default='order')),
                ('played_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'game_plays',
                'ordering': ['-played_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RewardTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('game_type', models.TextField()),
                ('win_level', models.TextField()),
                ('discount_type', models.TextField(choices=[('percentage', 'Percentage'), ('flat_amount', 'Flat Amount')])),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_discount_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valid_days', models.IntegerField(default=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('notify_whatsapp', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reward_tiers',
                'ordering': ['game_type', 'win_level'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GameReward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('game_type', models.TextField()),
                ('win_level', models.TextField()),
                ('whatsapp_sent', models.BooleanField(default=False)),
                ('whatsapp_delivered', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_play', models.OneToOneField(db_column='game_play_id', on_delete=django.db.models.deletion.CASCADE, related_name='reward', to='gaming.gameplay')),
                ('reward_tier', models.ForeignKey(blank=True, db_column='reward_tier_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards', to='gaming.rewardtier')),
                ('coupon', models.OneToOneField(blank=True, db_column='coupon_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_reward', to='coupons.coupon')),
            ],
            options={
                'db_table': 'game_rewards',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
    ]
