# Generated by Django 6.0.5 on 2026-06-08

import uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0005_external_api_keys'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('discount_type', models.TextField(choices=[('percentage', 'Percentage'), ('flat_amount', 'Flat Amount')])),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_discount_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('banner_image_url', models.TextField(blank=True, null=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'promotions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PromotionBroadcast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.TextField()),
                ('status', models.TextField(choices=[('sent', 'Sent'), ('failed', 'Failed')])),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.UUIDField()),
                ('promotion', models.ForeignKey(db_column='promotion_id', on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='promotions.promotion')),
            ],
            options={
                'db_table': 'promotion_broadcasts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PromotionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_items', to='inventory.product')),
                ('promotion', models.ForeignKey(db_column='promotion_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='promotions.promotion')),
                ('variant', models.ForeignKey(blank=True, db_column='variant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_items', to='inventory.productvariant')),
            ],
            options={
                'db_table': 'promotion_items',
                'managed': False,
            },
        ),
    ]
