# Generated by Django 6.0.5 on 2026-06-14 07:59

import uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_external_api_keys'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variant', models.ForeignKey(db_column='variant_id', on_delete=django.db.models.deletion.CASCADE, related_name='discount_suggestions', to='inventory.productvariant')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='discount_suggestions', to='inventory.product')),
                ('discount_score', models.IntegerField()),
                ('priority', models.TextField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium')])),
                ('reason_summary', models.TextField()),
                ('reasons', models.JSONField(default=dict)),
                ('suggested_discount_type', models.TextField()),
                ('suggested_discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('suggested_ends_days', models.IntegerField(default=14)),
                ('current_stock', models.IntegerField()),
                ('avg_monthly_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('days_since_last_order', models.IntegerField(blank=True, null=True)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('margin_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.TextField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('dismissed', 'Dismissed'), ('expired', 'Expired')], default='pending')),
                ('dismissed_until', models.DateTimeField(blank=True, null=True)),
                ('approved_promotion', models.ForeignKey(blank=True, db_column='approved_promotion_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_suggestion', to='promotions.promotion')),
                ('analysed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'discount_suggestions',
                'ordering': ['-discount_score', '-analysed_at'],
                'managed': False,
            },
        ),
    ]

