# Generated by Django 6.0.5 on 2026-06-20 14:20

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0007_reservation_coupons_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='QCPlatformCredentials',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('blinkit', 'Blinkit'), ('jiomart', 'JioMart')], max_length=20, unique=True)),
                ('fynd_username', models.TextField(blank=True, null=True)),
                ('fynd_access_token', models.TextField(blank=True, null=True)),
                ('fynd_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('blinkit_vendor_id', models.TextField(blank=True, null=True)),
                ('blinkit_receiver_code', models.TextField(blank=True, null=True)),
                ('blinkit_webhook_secret', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'qc_platform_credentials',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QCWarehouseMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('blinkit', 'Blinkit'), ('jiomart', 'JioMart')], max_length=20)),
                ('internal_facility_code', models.TextField()),
                ('platform_location_id', models.TextField()),
                ('mapping_type', models.CharField(choices=[('facility', 'Facility'), ('pincode', 'Pincode')], max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'qc_warehouse_mappings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QCPurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('blinkit', 'Blinkit'), ('jiomart', 'JioMart')], max_length=20)),
                ('platform_po_id', models.TextField(unique=True)),
                ('vendor_id', models.TextField(blank=True, null=True)),
                ('facility_code', models.TextField(blank=True, null=True)),
                ('po_status', models.CharField(choices=[('RECEIVED', 'Received'), ('VERIFIED', 'Verified'), ('DISPATCHED', 'Dispatched'), ('ASN_SENT', 'ASN Sent'), ('INWARDED', 'Inwarded'), ('CANCELLED', 'Cancelled')], default='RECEIVED', max_length=20)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('asn_reference', models.TextField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('inwarded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'qc_purchase_orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QCPlatformListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='qc_listings', to='inventory.product')),
                ('variant', models.ForeignKey(blank=True, db_column='variant_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_listings', to='inventory.productvariant')),
                ('platform', models.CharField(choices=[('blinkit', 'Blinkit'), ('jiomart', 'JioMart')], max_length=20)),
                ('platform_sku', models.TextField(blank=True, null=True)),
                ('platform_upc', models.TextField(blank=True, null=True)),
                ('asin_equivalent', models.TextField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('DRAFT', 'Draft'), ('VALIDATING', 'Validating'), ('SUBMITTED', 'Submitted'), ('PENDING_REVIEW', 'Pending Review'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('REJECTED', 'Rejected'), ('ERROR', 'Error')], default='DRAFT', max_length=20)),
                ('trace_id', models.TextField(blank=True, null=True)),
                ('submission_guid', models.UUIDField(blank=True, null=True)),
                ('validation_issues', models.JSONField(blank=True, default=list)),
                ('mrp_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('selling_price_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fssai_license', models.TextField(blank=True, null=True)),
                ('barcode_validated', models.BooleanField(default=False)),
                ('image_validated', models.BooleanField(default=False)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'qc_platform_listings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QCPOLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('po', models.ForeignKey(db_column='po_id', on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='quickcommerce.qcpurchaseorder')),
                ('variant', models.ForeignKey(blank=True, db_column='variant_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_po_items', to='inventory.productvariant')),
                ('platform_sku', models.TextField()),
                ('ordered_quantity', models.IntegerField()),
                ('delivered_quantity', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'qc_po_line_items',
                'managed': False,
            },
        ),
    ]
