# Generated by Django 6.0.5 on 2026-05-30 15:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gst_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.TextField(choices=[('UPI', 'UPI'), ('card', 'Card'), ('cash', 'Cash')])),
                ('payment_status', models.TextField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('hsn_code', models.TextField()),
                ('gst_slab', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('brand', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('subcategory', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('dietary_type', models.TextField(choices=[('veg', 'Vegetarian'), ('non-veg', 'Non-Vegetarian'), ('egg', 'Contains Egg'), ('none', 'Not Applicable')], default='none')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.TextField(unique=True)),
                ('barcode', models.TextField(blank=True, null=True, unique=True)),
                ('size', models.TextField(blank=True, null=True)),
                ('color', models.TextField(blank=True, null=True)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('weight_volume', models.TextField(blank=True, null=True)),
                ('net_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit_of_measure', models.TextField(blank=True, choices=[('kg', 'Kilograms'), ('g', 'Grams'), ('L', 'Litres'), ('ml', 'Millilitres'), ('pcs', 'Pieces'), ('pack', 'Pack')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'product_variants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('role', models.TextField(choices=[('customer', 'Customer'), ('staff', 'Staff'), ('manager', 'Manager')], default='customer')),
                ('phone_number', models.TextField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'profiles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('reserved_quantity', models.IntegerField()),
                ('expires_at', models.DateTimeField()),
                ('status', models.TextField(choices=[('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired')], default='active')),
            ],
            options={
                'db_table': 'reservations',
                'managed': False,
            },
        ),
    ]
