# Generated by Django 6.0.5 on 2026-06-06 11:49

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_multicategory_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_description', models.TextField()),
                ('bulk_quantity_used', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('bulk_unit', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'packaging_jobs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PackagingJobOutput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('packets_produced', models.IntegerField()),
                ('weight_per_packet', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('unit_of_measure', models.TextField(blank=True, null=True)),
                ('barcode_value', models.TextField(blank=True, null=True)),
                ('is_new_variant', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'packaging_job_outputs',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='packagingjob',
            name='source_variant',
            field=models.ForeignKey(
                blank=True,
                db_column='source_variant_id',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='packaging_jobs',
                to='inventory.productvariant',
            ),
        ),
        migrations.AddField(
            model_name='packagingjoboutput',
            name='job',
            field=models.ForeignKey(
                db_column='job_id',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='outputs',
                to='inventory.packagingjob',
            ),
        ),
        migrations.AddField(
            model_name='packagingjoboutput',
            name='variant',
            field=models.ForeignKey(
                db_column='variant_id',
                on_delete=django.db.models.deletion.RESTRICT,
                related_name='packaging_outputs',
                to='inventory.productvariant',
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='is_loose_commodity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='net_weight_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='unit_of_measure',
            field=models.TextField(choices=[
                ('unit', 'Unit'),
                ('kg', 'Kilograms'),
                ('g', 'Grams'),
                ('litre', 'Litres'),
                ('ml', 'Millilitres'),
                ('L', 'Litres (Legacy)'),
                ('pcs', 'Pieces'),
                ('pack', 'Pack')
            ], default='unit'),
        ),
    ]
