# Generated by Django 6.0.5 on 2026-06-06 13:23

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_loose_commodity_repackaging'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.TextField(blank=True, null=True, unique=True)),
                ('vendor_name', models.TextField(blank=True, null=True)),
                ('vendor_gstin', models.TextField(blank=True, null=True)),
                ('issued_at', models.DateField(blank=True, null=True)),
                ('gcs_object_path', models.TextField()),
                ('status', models.TextField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('review', 'Needs Review'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending')),
                ('uploaded_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'purchase_invoices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice', models.ForeignKey(db_column='invoice_id', on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='inventory.purchaseinvoice')),
                ('sku', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gst_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('needs_review', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'invoice_line_items',
                'managed': False,
            },
        ),
    ]
