# Generated by Django 6.0.5 on 2026-06-06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_invoicelineitem_purchaseinvoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('partner_name', models.TextField()),
                ('key_hash', models.TextField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'external_api_keys',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='carrier_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_reference',
            field=models.TextField(blank=True, null=True),
        ),
    ]
