# Generated by Django 6.0.5 on 2026-06-08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_external_api_keys'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='effective_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='promotion',
            field=models.ForeignKey(blank=True, db_column='promotion_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='promotions.promotion'),
        ),
    ]
