# Generated by Django 6.0.5 on 2026-06-19 15:32

import uuid
from django.db import migrations, models


import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0007_reservation_coupons_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonCredentials',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seller_id', models.CharField(max_length=255, unique=True)),
                ('lwa_client_id', models.CharField(max_length=255)),
                ('lwa_client_secret', models.TextField()),
                ('lwa_refresh_token', models.TextField()),
                ('region', models.CharField(choices=[('NA', 'North America'), ('EU', 'Europe'), ('FE', 'Far East')], default='EU', max_length=2)),
                ('primary_marketplace_id', models.CharField(max_length=50)),
                ('authorized_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'amazon_credentials',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AmazonListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='amazon_listings', to='inventory.product')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('asin', models.CharField(blank=True, max_length=10, null=True)),
                ('marketplace_id', models.CharField(max_length=50)),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('ACTIVE', 'Active'), ('INVALID', 'Invalid'), ('ERROR', 'Error'), ('SUPPRESSED', 'Suppressed')], default='PENDING', max_length=20)),
                ('submission_id', models.UUIDField(blank=True, null=True)),
                ('validation_issues', models.JSONField(blank=True, default=list)),
                ('price_synced', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity_synced', models.IntegerField(default=0)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'amazon_listings',
                'managed': False,
            },
        ),
    ]
